###
GET http://localhost:8080/

###
GET http://localhost:8080/hello/ricid/kumbara
Content-Type: application/json

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "first_name": "Ricid",
  "last_name": "Kumbara"
}

# Todos

###
GET http://localhost:8080/todos
Content-Type: application/json

###
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Learn Rust",
  "description": "Learn rust in 1 week"
}

###
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "id": 1,
  "title": "Learn Rust Update-001",
  "description": "Learn rust in 1 week Update-001"
}